baseURL = "https://iamleandrooooo.github.io/"
languageCode = "en-us"
title = "Leandro's Code Cave"
theme="archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	subtitle = "Pentesting, Malware Development, Malware Analysis, and Reversing stuff."

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
